defaults:
  - _self_ 
  - callbacks: default
  - data/gender_datapipe: default_datapipe
  - data/module: voxceleb
  - network: wavlm
  - optim/algo: adam
  - optim/schedule: constant
  - optim/loss: cross_entropy
  - trainer: trainer_gpu

# directory for slurm and hydra logs
log_folder: ${oc.env:LOG_FOLDER}

# random seed used by the experiment
seed: 42133724

# whether to fit model
fit_model: True

# whether to evaluate model
eval_model: True

# whether to load the weight of the networks from a checkpoint
load_network_from_checkpoint: null

# whether to log to wandb
use_wandb: ${oc.decode:${oc.env:USE_WANDB}}

# project name (useful for giving a name to log directories)
project_name: gender_recognition

# experiment name
# (:) indicates it needs to be resolved
experiment_name: ${random_name:}

# tag to add to the experiment dashboard for easy filtering
# of certain experiment
date_tag: ${now:%Y-%m-%d}
tag: null

# config variables for hydra
hydra:
  run:
    # set root output directory
    dir: ${log_folder}/${project_name}/run/${now:%Y-%m-%d_%H-%M-%S}/${experiment_name}
  sweep:
    # set root output directory
    dir: ${log_folder}/${project_name}/sweep/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${experiment_name}
  job:
    chdir: true